# Generated by Django 4.0.5 on 2022-09-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoloading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargotable',
            name='box_num',
            field=models.PositiveIntegerField(),
        ),
    ]
