# Generated by Django 4.0.5 on 2022-09-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargoloading', '0002_alter_cargotable_box_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoTable',
        ),
    ]
