# Generated by Django 4.0.5 on 2022-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoloading', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargolist',
            name='box',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cargolist',
            name='cbm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cargolist',
            name='chargeable_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cargolist',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cargolist',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
