# Generated by Django 4.0.5 on 2022-09-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoloading', '0005_cargolist_box_cargolist_cbm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_box', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('ini_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cargo_type', models.CharField(max_length=100, null=True)),
                ('csvFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='cargolist',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cargolist',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cargolist',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cargolist',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
